[36] translate "minutes" and "seconds" in time inputs
jakubmanczak/debates pull request #77
Opened 2024-06-14 17:57 UTC by Mateusz-Dobrzynski

Resolves #36.

I ended up implementing non-standard Polish "minutes" conjugation, as this software is targeted primarily at Polish audience. It is 100% correct only with numbers below 12, because Oxford debate speeches usually don't exceed 5 minutes anyway.

2024-06-14 20:10 UTC, jakubmanczak commented
Now that we actually want to tackle this translation at all, I think we do it right.
The approach I'd favor is moving this to `@lib` and implementing a function that returns the appropriate string - something like `useLocalisedNumerosityNoun` which would take in a number and return the appropriate noun.

2024-06-14 20:12 UTC, jakubmanczak requested changes

2024-06-14 20:12 UTC, jakubmanczak commented on src/components/TimeInput.tsx
> +          {minutesCount == 1 ? ` ${minutesSingular}` : ` ${minutesPlural}`}
Doing the following would eliminate this logic, and make it reusable.

---
Now that we actually want to tackle this translation at all, I think we do it right.
The approach I'd favor is moving this to @lib and implementing a function that returns the appropriate string - something like useLocalisedNumerosityNoun which would take in a number and return the appropriate noun.

2024-06-17 15:01 UTC, jakubmanczak requested changes
I suggested some changes, along with a question about the way we intend to handle things: is holding default versions of grammatical numbers as strings that we then either return unchanged or replace in special cases really the way to go? Would it not be better if we stored these default cases in `@/lib/file.ts`, and returned "m" or "s" as units for unsupported ones?

2024-06-17 17:10 UTC, Mateusz-Dobrzynski commented
While I agree that supporting more cases and better names are good suggestions, omitting curly brackets is not something I would do. In principle, it makes debugging more difficult.

2024-06-17 22:35 UTC, jakubmanczak commented
I agree with the general sentiment that the omission of curlies should be avoided sometimes. Particularly, when the statement you'd wrap is in the next line – that's when you're prone to writing more and messing up. And the things Javascript lets you do without ever writing `{}` is criminal. But no obedience to a semantics rule should be absolute. Here, it makes sense to break it. There's nothing to debug here, the logic is simple, all of it is just returns anyway, none of it is hard to follow, no reason to double the code's size on your screen, lost conciseness, readability and clarity etc.

Anyway, why are we using top level PR comments to discuss a specific suggestion when the reply feature exists?

2024-06-19 16:42 UTC, Mateusz-Dobrzynski commented on src/data/strings.json
> +    "de": "und"
As long as returning the answer doesn't require creating any additional logic, I'd rather reuse the code we already have. Special cases require new logic (that's why they're special, so I covered them in the library.

2024-06-19 22:22 UTC, jakubmanczak requested changes

2024-06-19 22:22 UTC, jakubmanczak commented on src/components/TimeInput.tsx
> +  const minutesCardinalNumeral = useLocalizedGrammaticalNumber(
```suggestion
  const minutesGrammaticalNumber = useLocalizedGrammaticalNumber(
```

2024-06-19 22:22 UTC, jakubmanczak commented on src/components/TimeInput.tsx
> +          {`  ${minutesCardinalNumeral}`}
```suggestion
          {`  ${minutesGrammaticalNumber}`}
```

2024-06-19 22:22 UTC, jakubmanczak commented on src/data/strings.json
> +    "en": "minute",
```suggestion
    "en": "minute",
    "pl": "minuta",
```

2024-06-19 22:22 UTC, jakubmanczak commented on src/data/strings.json
> +    "en": "minutes",
```suggestion
    "en": "minutes",
    "pl": "minuty",
```

2024-06-19 22:22 UTC, jakubmanczak commented on src/data/strings.json
> +    "en": "seconds",
```suggestion
    "en": "seconds",
    "pl": "sekund",
```

2024-06-19 22:22 UTC, jakubmanczak commented on package.json
> +  ]
Don't know what this is but I know I don't want it here. Revert please.

2024-06-21 19:29 UTC, jakubmanczak approved these changes
✅✅🚀😍🔥🔥🔥🔥

2024-06-21 19:29 UTC, jakubmanczak commented
oh no package lock conflict

2024-07-03 14:53 UTC, merged